# GoReleaser configuration for try
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: try
    main: .
    binary: try
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*
      - docs/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: xpzouying
    name: try
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

# Homebrew tap (requires separate repo: homebrew-tap)
brews:
  - name: try
    repository:
      owner: xpzouying
      name: homebrew-tap
    homepage: "https://github.com/xpzouying/try"
    description: "Manage experimental project directories"
    license: "MIT"
    install: |
      bin.install "try"
    test: |
      system "#{bin}/try", "--version"
